[package]
name = "meatpack"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A Rust implementation of the MeatPack algorithm for encoding gcode."
repository = "https://github.com/jamesgopsill/meatpack"
readme = "README.md"
keywords = ["gcode", "no_std", "MEX", "FDM", "3d_printing"]

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
