[package]
name = "meatpack"
version = "0.0.1"
edition = "2021"

[features]
default = ["no_std"]
std = []
no_std = []

[dependencies]
no_std_io = { version = "0.6.0", default_features = false, features = [
	"nightly",
] }
